### ISSUE TITLE
CoolProp.setLibraryPath is not a function

### ISSUE THREAD

**Issue by rzdrojewski** [kansaandre/coolprop_js_npm#1]
Hi,
I am currently working on integrating Coolprop in a NodeJS app i found your NPM package.

It works well but only if i remove the following line in the index.js file 
`CoolProp.setLibraryPath('./coolprop_sources');`

If I leave this line i get the following error : `CoolProp.setLibraryPath is not a function`

Could you explain why is this line needed ?

Thanks

**Comment by kansaandre** [comment]
Hi!

Thank you for letting me know, I made a mistake and accidentally included line in Git/npm version, did not notice error myself as my local version which I use did not have this issue. Commit have fixed it and will update npm version now with the fix. 

![image](https://github.com/kansaandre/coolprop_js_npm/assets/115343379/f0496496-72ba-4cb7-9835-8796c57f0a11)
